### ISSUE TITLE
Issue in Angular 4 Build 

### ISSUE THREAD

**Issue by Bhole007** [dolce/iziToast#103]
It's working fine with ng serve
but
It's throwing error at the time of build.

" Error : Cannot find module 'ng2-izitoast' "

Is it compatible for angular 4 ?

**Comment by dolce** [comment]
Please use the Angular project repository.
https://github.com/plauzul/ng2-izitoast

**Comment by Bhole007** [comment]
**Thanks**  @dolce , I'll check "https://github.com/plauzul/ng2-izitoast"
