### ISSUE TITLE
Uncaught ReferenceError: iziToast is not defined

### ISSUE THREAD

**Issue by RudolfFussek** [dolce/iziToast#104]
Hey,

I have the error **Uncaught ReferenceError: iziToast is not defined**.

My Code from example:

`<script>
            iziToast.show({
                title: 'Hey',
                message: 'What would you like to add?'
            });
        </script>`

Thanks for help!

**Comment by dolce** [comment]
Hello, review your code, you did not properly import the library.

**Comment by RudolfFussek** [comment]
izitoast/dist/css/iziToast.min.css
izitoast/dist/js/iziToast.min.js

Not right?

**Comment by RudolfFussek** [comment]
I have found the problem. Thanks!

**Comment by iliess** [comment]
What was your problem ?

**Comment by seddighi78** [comment]
I have the same problem ...
How did you resolve your problem?
