### ISSUE TITLE
[documentation] bug in "hide" method

### ISSUE THREAD

**Issue by camiant** [dolce/iziToast#105]
**WRONG**

```
iziToast.hide({
    transitionOut: 'fadeOutUp'
}, toast);
```

**CORRECT**
```
iziToast.hide(toast, {
    transitionOut: 'fadeOutUp'
});
```

**Comment by dolce** [comment]
No, which version?
Use **v1.3.0**, thanks.
`$iziToast.hide = function (options, $toast, closedBy)`

**Comment by camiant** [comment]
I'm using 1.2.0.. latest version in npm.

**Comment by brunonetadmin** [comment]
I´m using the latest version from the site (1.3.0), but the way its in documentation don´t work, the way "Camiant" corrects, works fine for me.

The option in documentation fires this error when trying to hide: 
Uncaught TypeError: Cannot read property 'contains' of undefined
