### ISSUE TITLE
Update NPM package to 1.3

### ISSUE THREAD

**Issue by HamedFathi** [dolce/iziToast#107]
Please update NPM package to 1.3

**Comment by fillon** [comment]
Any reason why 1.3 is not available in NPM ?
Is 1.3 safe to use in production environment ?

**Comment by dolce** [comment]
Could you update your package and run the tests?
https://github.com/dolce/iziToast/releases/tag/v1.3.0

**Comment by eman1986** [comment]
is there something special you have to do to run non-published versions of npm?

**Comment by ZerglingGo** [comment]
I think you should publish 1.3.0 first and then fix the bug next patch version.

**Comment by dolce** [comment]
**v1.3.0** published.
https://www.npmjs.com/package/izitoast
