### ISSUE TITLE
Can't pause and resume the timer (Error: Cannot read property 'querySelector' of undefined)

### ISSUE THREAD

**Issue by codespacing** [dolce/iziToast#108]
Hi,

I use the same code your proposed here #71 but still have issues. I tried version 1.2 & 1.3.

Error:

> Uncaught TypeError: Cannot read property 'querySelector' of undefined
> at Object.$iziToast.progress (iziToast.js:394)
> at HTMLButtonElement. (iziToast.js:917)

The code:

```
iziToast.show({
    timeout: 10000,
    close: false,
    overlay: true,
    toastOnce: true,
    pauseOnHover: false,
    id: 'question',
    message: 'Working with time',
    position: 'center',
    buttons: [
        ['<button><b>RESUME</b></button>', function (instance, toast) {
           
            instance.progress(toast).resume();

        }, true],
        ['<button>PAUSE</button>', function (instance, toast) {

            instance.progress(toast).pause();

        }]
    ]
});
```

Can you please help with this?

**Comment by dolce** [comment]
@codespacing @rossdomke 
Please, see if it's working normally now.
https://github.com/dolce/iziToast/releases/tag/v1.3.0

**Comment by codespacing** [comment]
Hi @dolce 

Yes it works now using this code:

`
iziToast.show({
    timeout: 10000,
    close: false,
    overlay: true,
    toastOnce: true,
    pauseOnHover: false,
    id: 'question',
    message: 'Working with time',
    position: 'center',
    buttons: [
        ['<button><b>RESUME</b></button>', function (instance, toast) {
           
            instance.progress({}, toast).resume();

        }, true],
        ['<button>PAUSE</button>', function (instance, toast) {

            instance.progress({}, toast).pause();

        }]
    ]
});													
`
Thanks a bunch for the update.
