### ISSUE TITLE
Button hide no longer works from 1.2 to 1.3

### ISSUE THREAD

**Issue by dougroutledge** [dolce/iziToast#109]
After update to 1.3, the code to hide the toast after a a yes/no button click no longer works.  This error is thrown.

iziToast.min.js:6 Uncaught TypeError: Cannot read property 'add' of undefined
    at Object.e.hide (iziToast.min.js:6)
    at ciscoconsole.min.js:1
    at HTMLButtonElement.<anonymous> (iziToast.min.js:6)

**Comment by dolce** [comment]
How are you using?

**Comment by dolce** [comment]
$iziToast.hide = function (options, $toast, closedBy)

**Comment by Neoscopia** [comment]
Actually, the function signature not matches what you say.
The options and toast parameters are inverted, so it causes the function hide to not work.
```javascript
$iziToast.hide = function ($toast, options, closedBy) {
	...
	> $toast.classList.add(PLUGIN_NAME+'-closing');
	...
}
```
If you swap the two parameters, everything works again.

**Comment by dolce** [comment]
Negative. This is the correct signature of the function:
`$iziToast.hide = function (options, $toast, closedBy) {`
It has been changed for some time. is the default like all other methods.

**Comment by Neoscopia** [comment]
Hm, it's because i have reinstalled your package with version 1.2, so it's break as i copy from documentation which use the latest signature. Thanks for you reactivity and your amazing work on this project

**Comment by dolce** [comment]
Thank you. I will correct a few more things in v1.3 and will soon publish in NPM.
Stay tuned.
