### ISSUE TITLE
Wrong scope when trying to hide

### ISSUE THREAD

**Issue by cberescu** [dolce/iziToast#110]
When calling 
`instance.hide({ transitionOut: 'fadeOut' }, toast, 'button');`

On this line  
`var settings = extend(this.settings, options || {});`

`this.settings` is empty 

i think _this.settings_ should contain the defaults.

**Comment by dolce** [comment]
Try version 1.3.

**Comment by cberescu** [comment]
that is the version i tried.

**Comment by dolce** [comment]
Send me your example.
