### ISSUE TITLE
positions doesnt work in rtl mode

### ISSUE THREAD

**Issue by molikh** [dolce/iziToast#115]
i cant say if it is a bug or not.

problem is when i use rtl mode position bottomLeft dosent works.
**consider this when i use rtl mode i already set my body dir="rtl"** 
when body is ltr, position works fine.
so my question is how use rtl mode when my body element have dir="rtl" attribute?

**Comment by dolce** [comment]
I already found the problem.
You can test this fix in version 1.3.0
Thank you.
