### ISSUE TITLE
[Feature Request] Align buttons to be inline with text when overlay property is set true.

### ISSUE THREAD

**Issue by GamingSabre** [dolce/iziToast#116]
Hi,
I have to say that this and your modal plugin are by far the best and most beautiful implementations on the net!

I have been playing around with using the overlay option to use as a confirmation popup.
I noticed on your online example that when you have an input and a button together everything is inline with the text.
But when you have only buttons they sit below the text, is there a way to make is an option?

Below is a work around that I came across to achieve what I am looking for using a hidden input.

```
iziToast.warning({
    layout: 1,
    timeout: false,
    close: false,
    closeOnEscape: true,
    overlayClose: true,
    overlay: true,
    toastOnce: true,
    id: 'question',
    title: 'Delete Item?',
    message: 'There\'s no going back!',
    position: 'center',
    transitionIn: 'flipInX',
    transitionOut: 'flipOutX',
    inputs: [
        ['<input type="hidden">']
    ],
    buttons: [
        ['<button style="width: 50px;">Yes</button>', function (instance, toast) {
            instance.hide({ transitionOut: 'flipOutX' }, toast, 'button');
            deleteArea(id);
        }],
        ['<button style="width: 100px;"><b>Cancel</b></button>', function (instance, toast) {
            instance.hide({ transitionOut: 'flipOutX' }, toast, 'button');
        }]
    ]
});
```

**Comment by dolce** [comment]
Fixed.
You can retest version 1.3.

**Comment by GamingSabre** [comment]
Excellent work!
I have created a [stackblitz](https://stackblitz.com/edit/izitoast-warning?embed=1&file=index.js) page and can confirm that the issue has been fixed.
Many Thanks :+1:
