### ISSUE TITLE
[question] iziToast on cdnjs

### ISSUE THREAD

**Issue by sysiler** [dolce/iziToast#118]
@dolce Are you going to publish the latest 1.3 release on https://cdnjs.com/libraries/izitoast or is download the only way at the moment?
Great lib btw 👍  I really like the new input feature!

**Comment by dolce** [comment]
Hello @sysiler.
And I have already said before, I need several users to test the new version. if it is stable, then yes I publish in the npm.
Thanks.

**Comment by ahjorth** [comment]
Is there a way to see documentation for 1.2? Since it's not up on NPM, seems strange to update the official documentation to a non-stable version. It really confused me at least

**Comment by dolce** [comment]
**v1.3.0** published.
https://www.npmjs.com/package/izitoast
