### ISSUE TITLE
Toasts don't close on timeout

### ISSUE THREAD

**Issue by Olivier61** [dolce/iziToast#122]
Hi, 

When creating multiple toast at short interval some are not closing at timeout.

You can reproduce it at http://izitoast.marcelodolce.com/#Options
- click 4 or 5 times on an example.
- e.g. "Example" next to  "buttons[] You can specify an array of buttons. Example" and wait ...

Most of the times one toast (or more) are not closed, usually the last opened.
Moving the mouse over and out of the toast sometimes makes it close, but not always.

Reproduced on Safari (11.0.3), Firefox (58.0.2), Chrome (64.0.32) all on macOS High Sierra

Anyway to fix this ?

Thanks !

Olivier

**Comment by dolce** [comment]
Hello. I'm aware of the problem. I'll publish corrections soon.

**Comment by dolce** [comment]
Could you update your package and run the tests?
https://github.com/dolce/iziToast/releases/tag/v1.3.0

**Comment by dolce** [comment]
Could you update your package and run the tests?

**Comment by Olivier61** [comment]
Hi, it's indeed fixed. 
Great tool and great support !
Thanks.
