### ISSUE TITLE
Outdated documentation for instance.hide

### ISSUE THREAD

**Issue by zachsteffens** [dolce/iziToast#125]
Throughout the demo page you have this code (or some variant) as an example of how to programmatically close the toast.
`instance.hide({ transitionOut: 'fadeOut' }, toast, 'button');`

Seems like this is out of order, the hide method signature looks like this 
`$iziToast.hide = function ($toast, options, closedBy) {`

So the options need to be the second parameter.  Not a huge issue and any decent Dev can figure it out quickly.  Just wanted to call it to your attention.

**Comment by spankie** [comment]
Really threw me off guard at first.
