### ISSUE TITLE
Implementation Issue (in HTML using Spring Framework)

### ISSUE THREAD

**Issue by Khechoyan-Yuri** [dolce/iziToast#128]
![izitoast_dark](https://user-images.githubusercontent.com/21959398/38450398-aa53db2a-39e2-11e8-847a-681d0b953522.JPG)

I am trying to implement iziToast to a web page that I am building. Shown above is the iziToast that I would like to implement. Web-page works off of the Spring Framework. I am not using anything advanced (Bootstrap, ReactJS, Angular 2, etc.) I am coding in simple HTML, CSS, & JS. I have followed the instructions to import iziToast:

**1. HTML › Include the CSS files from the dist folder in the head section:**
`<link rel="stylesheet" href="iziToast.min.css">`

**2. HTML › Include the JS file before the scripts:**
`<script src="iziToast.min.js" type="text/javascript"></script>`

**3. JS › Basic example:**
`iziToast.show({
    title: 'Hey',
    message: 'What would you like to add?'
});`

What I want to know is, what code is needed in order for the iziToast to appear on the web-page. That code was not given through: http://izitoast.marcelodolce.com/

Should it be inside of a `div`? Should I be calling a class inside a div (e.g. `div class="name of class"/>`)?

**Comment by dolce** [comment]
No, you only need to include the JS and CSS files and then execute the statement to open the toast.
