### ISSUE TITLE
[Feature Request] Add Option for dismiss duplicates.

### ISSUE THREAD

**Issue by ggedde** [dolce/iziToast#140]
I know that you have an option for `toastOnce`, but it requires setting an ID.
I would rather not have to set an ID for every toast and instead have the system hash the 'message', 'type', 'title', and 'options' and check to make sure that toast is not already being displayed.

Or it would be nice if I could hook into the default ID and if is set to 'null' then I can add my own unique id based on the toast object.

Thanks

**Comment by dolce** [comment]
v1.4.0 released. You can check out this and other features. thank you.
https://www.npmjs.com/package/izitoast
