### ISSUE TITLE
Space buttons

### ISSUE THREAD

**Issue by ap-prog** [dolce/iziToast#143]
To space multi-buttons in a dialog I've been using

onOpening: function(instance, toast) {
  toast.querySelectorAll(".iziToast-buttons-child").forEach(function(el) { el.style.marginRight = "1em"; });
}

It would be nice if there was a setting that I could use to set the spacing for me (all my dialogs tend to have the same default settings for a project.)

**Comment by dolce** [comment]
You can add a class to handle this.
