### ISSUE TITLE
hide($toast) does not work as documented - options is required as first arg (breaking change)

### ISSUE THREAD

**Issue by danwad** [dolce/iziToast#150]
Version: 1.3.0 (npm)

Documentation says hide can be used with a single argument but in fact the options parameter is required as the first argument.

```
var toast = document.querySelector('.iziToast'); // Selector of your toast
 
iziToast.hide(toast);
```

This is a breaking change from a previous version.

**Comment by dolce** [comment]
`iziToast.hide({}, toast);`

Fixed, thank you.
