### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by MathMesquita** [dolce/iziToast#16]
Opa, boa tarde,

Está ocorrendo algum erro no npm, o modulo do iziToast não ta sendo encontrado...

https://runkit.com/5843226183edc1001385297d/5843226183edc1001385297e

Pode ver ai no teste online do npm.

Abçs

**Comment by dolce** [comment]
Agradeço o feedback @MathMesquita . Parece que o package.json estava com erro mesmo, tente novamente instalando o modulo nesta versão:
`npm i izitoast@1.0.2-c`
Avisae se estiver ok! abraço!
