### ISSUE TITLE
Split title and message into two lines

### ISSUE THREAD

**Issue by leduonggithub** [dolce/iziToast#160]
Thank you for creating iziToast, it is really good, i guess it will become the best notifications package in near future.  But when i use it, i don't find any option to set title and message into two separate lines, currently it always show in one line. This isn't so good in small device screens, and sometimes it don't look like nice. Could you help me ?

**Comment by Feras94** [comment]
Hello @leduonggithub, you can use HTML strings to split the message and the title:
```
iziToast.show({
    title: 'First Line<br>Second Line',
    message: 'Message Line One<br>Message Line Two',
});
```

**Comment by leduonggithub** [comment]
@Feras94  Thank you so much. It is really good, i didn't think that it can render html tag before
