### ISSUE TITLE
html in message?

### ISSUE THREAD

**Issue by chiqui3d** [dolce/iziToast#22]
Is it possible to add html in messages?

**Comment by gabrielferreiraa** [comment]
@dolce é possível ?

**Comment by dolce** [comment]
É sim @gabrielferreiraa, adicionei essa feature nas novas autalizações.

**Comment by gabrielferreiraa** [comment]
Blz, atualizei aqui e deu certo :D Valeuu !!

**Comment by nam-co** [comment]
Hi, I was wondering how to use this feature?

**Comment by dolce** [comment]
It's simple @nam-co 
```js
message: 'html <b>example</b>?'
```

**Comment by guimaker** [comment]
This displays 'html' as part of my message....  how do I suppress that?

**Comment by guimaker** [comment]
Figured it out....   message: '<html> your stuff here...   </html>'
