### ISSUE TITLE
Close on ESC

### ISSUE THREAD

**Issue by pablo-pacheco** [dolce/iziToast#24]
Is there an option to close on Escape key press?
Thank you

**Comment by pablo-pacheco** [comment]
I'm doing like this and it's working. 

```
$(document).keyup(function(e) {
	if (e.keyCode == 27) {
		iziToast.hide({}, '.iziToast');
	}
});
```
If is there a better way please let me know. Thanks

**Comment by dolce** [comment]
@pablo-pacheco. There is no option to close the Toast with the ESC key.
The idea of iziToast is to be something minimalistic and fast, and to allow you to open several at the same time. So I do not think this implementation would be feasible. But I will analyze it anyway.
Thank you!
