### ISSUE TITLE
rtl small fix -> text-align still is left

### ISSUE THREAD

**Issue by molikh** [dolce/iziToast#26]
text-align still is left on message

![capture](https://cloud.githubusercontent.com/assets/11052733/22778408/137089b8-eecc-11e6-9085-52902a7796f3.PNG)

i fix it with this change :
`.iziToast-rtl .iziToast-body p, .iziToast-rtl .iziToast-body strong : {
text-align: right;
}`
and result:
![capture](https://cloud.githubusercontent.com/assets/11052733/22778542/955ddf3e-eecc-11e6-9601-dda6b43fcbc8.PNG)

but still i think would be nice if we have an option for font-size

thanks for your great work

**Comment by dolce** [comment]
Thank you for your contribution.
