### ISSUE TITLE
Conflict with iziModal CSS

### ISSUE THREAD

**Issue by rktaiwala** [dolce/iziToast#28]
When both iziModal and iziToast are used on the same page, the iziModal CSS animations are affected by the iziToast CSS.

**Comment by dolce** [comment]
It has been fixed and will be updated soon, thank you.

**Comment by MythTheWolf** [comment]
Has this been updated yet? Still got CSS issues

**Comment by dolce** [comment]
In the Bower not yet.

**Comment by MythTheWolf** [comment]
Ah,ok.

**Comment by mourad1081** [comment]
Still got the issue here, I've downloaded the sources directly from the repo.
When both iziModal and iziTast run on the same page, they are conflicting and iziToast bugs a lot

**Comment by mourad1081** [comment]
EDIT : Solved the issue. I had to use the non minified source in order to not have any conflict. I minified them myself and everything works fine
