### ISSUE TITLE
Allow to re-open toast?

### ISSUE THREAD

**Issue by ErinPo** [dolce/iziToast#31]
Very nice design and animations! I would love to see an option for a toast to collapse to just it's icon on (auto-)closing, allowing user to re-open it on click. I guess the icon could float on the edge of the screen on larger screens, respecting the existing position parameter (bottomRight, bottomLeft, topRight, topLeft, topCenter, bottomCenter). Some animation could make it clear to the user that the icon came out of the collapsed toast. What do you think?

**Comment by chekovsky** [comment]
I never saw a toast that needed to be reoppened. Wouldn't be better if you create a custom component to handle this need? Your component would then fire a new toast when clicked.

**Comment by dolce** [comment]
Exactly @chekovsky, thanks! @ErinPo The goal of a toast is not that.
But you can do the control in your code.

**Comment by wgch** [comment]
This should be closed if it is outside the scope.
