### ISSUE TITLE
Incorrect pattern for buttons object 

### ISSUE THREAD

**Issue by xereda** [dolce/iziToast#33]
Example structure for the "Buttons" object.

The sample structure for the "buttons" object does not appear to be in an acceptable pattern for javascript. 

Take the example from the official iziToast page.

![captura de tela 2017-02-28 as 09 22 04](https://cloud.githubusercontent.com/assets/14337850/23405106/66779fc8-fd97-11e6-83e8-1a40702d0f81.png)

**Comment by dolce** [comment]
What is incorrect? Is not working?

**Comment by xereda** [comment]
It's working perfectly. I just thought it might create an inconsistency in the future. A javascript object pattern can be considered in the suggestion below.

```js

Buttons: [
   {'<Button> Ok </ button>': (instance, toast) => {alert ("Hello world!")
   {'<Button> Close </ button>': (instance, toast) => {
       Instance.hide ({
         TransitionOut: 'fadeOutUp',
         OnClose: (instance, toast, closedBy) => {
           Console.info ('closedBy:' + closedBy) // btn2
         }
       }, Toast, 'close', 'btn2')
     }
   }
},

```

Regardless of anything, its great job!

**Comment by dolce** [comment]
Thanks for the suggestion @xereda, I will be making some improvements soon.

**Comment by dolce** [comment]
Hello @xereda, I'm working on this latest version now. Would you like to contribute by making a Commit with a better pattern to the buttons? Thanks!

**Comment by chekovsky** [comment]
@xereda code is ES6. @dolce code is vanilla JS. Since not everyone (yet) is using ES6, I think vanilla JS for documentation is still better than a language that yet need to be transpiled to work.

Using vanilla JS I can get @dolce example working with ease.

**Comment by xereda** [comment]
@chekovsky Its true! Tks for feedback.
