### ISSUE TITLE
Settings ignores zIndex

### ISSUE THREAD

**Issue by hkelly93** [dolce/iziToast#34]
In my settings I set the zIndex to be the highest zIndex in my app

`iziToast.settings({
    position: 'bottomRight',
    timeout: 4000,
    zIndex: 9999999999
});`

This gets ignored and I see the div

`<div class="iziToast-wrapper iziToast-wrapper-bottomRight" style="z-index: 999999;">...</div>`

**Comment by dolce** [comment]
Hello @hkelly93. The correct is lowercase (**zindex**: ...), thanks.
