### ISSUE TITLE
Balloon ignores custom background color

### ISSUE THREAD

**Issue by elporfirio** [dolce/iziToast#37]
Balloon takes, the original color for show, success, error... etc.

But if you customize **backgroundColor** option, the Balloon (little triangle) continue adopting original color.

**Request:** 
- OPTA: IF exist a custom background Color, take custom color.
- OPTB: Add "backgroundBalloonColor" option

thank you :)

**Comment by dolce** [comment]
Obrigado @elporfirio, isso já foi corrigido e será atualizado em breve.
