### ISSUE TITLE
Toast is behind Bootstrap navbar fixed top !

### ISSUE THREAD

**Issue by lyquocnam** [dolce/iziToast#4]
![image](https://cloud.githubusercontent.com/assets/8347826/20513775/c20fef72-b0ba-11e6-9f3d-48dfafa94d5f.png)

How to send it to front or margin, padding from top ?

**Comment by khaivngo** [comment]
The easiest way will be to modify the iziToast.css and increasing the z-index for the .iziToast-wrapper. Developer should take into account people using iziToast with Bootstrap.

**Comment by lyquocnam** [comment]
thanks @khaivngo it's work !
