### ISSUE TITLE
Is is possible to set max-with

### ISSUE THREAD

**Issue by pascalf22** [dolce/iziToast#42]
Hello !
Is it possible to set max-with of the toast?
because sometimes the title and message are couple of words so it make the toast so long....

Is-it possible ?

thanks

**Comment by dolce** [comment]
Hello @pascalf22 . Just for css.
But I'll be adding this option soon, thanks.

**Comment by pascalf22** [comment]
Wow ok thanks for your quick reply !!
Thanks :)

**Comment by dolce** [comment]
@pascalf22. I updated the documentation and the repository. Check it

**Comment by pascalf22** [comment]
Hi !!! Great !! I really appreciate !!
Have agreat weekend :)

Thanks a lot :)

**Comment by dolce** [comment]
You're welcome! enjoy!
