### ISSUE TITLE
Is it possible to change the color of the close icon?

### ISSUE THREAD

**Issue by guylhermetabosa** [dolce/iziToast#45]
I know that is possible to change the color of the icon, but what about the close icon, i'd like to turn it white.

**Comment by dolce** [comment]
I apologize for the delay.
You can use the option:
`color: 'dark';`

**Comment by guylhermetabosa** [comment]
Are you sure, Looks like the close icon is a base64.

**Comment by dolce** [comment]
Using this option you change the theme color of it, to black or white.

**Comment by stiltet** [comment]
This don't work. The color don't change when setting `color: 'dark'.`
