### ISSUE TITLE
global onClose should be called anytime the notification is closed

### ISSUE THREAD

**Issue by cberescu** [dolce/iziToast#48]
I don't know if this is a issue or is by design, but, when i call instance.hide() from a button shouldn't the global onClose be also called ?

**Comment by VersatilityWerks** [comment]
Why is this closed? I have the same concern.

**Comment by cberescu** [comment]
found this in the docs : 

document.addEventListener('iziToast-close', function(data){
    if(data.settings.class == 'test'){
        console.info('EventListener iziToast-close');
        console.info(data.detail.closedBy);
    }
});
