### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by VersatilityWerks** [dolce/iziToast#49]
npm install installs the v1.1.0

**Comment by VersatilityWerks** [comment]
https://www.npmjs.com/package/izitoast

**Comment by chekovsky** [comment]
v1.1.1 here instead of v1.1.2 :disappointed:

**Comment by VersatilityWerks** [comment]
Yea, I see that now. Still a version behind and missing a couple things I really needed. I ended up installing it manually.

**Comment by dolce** [comment]
Guys, download from the repository:
Https://github.com/dolce/iziToast/releases/tag/v1.1.2

I will update some settings before registering pro _npm/bower_.
Thanks!

**Comment by VersatilityWerks** [comment]
I think NPM has an auto-update feature? I've never had to update my jAlert repo on there: https://www.npmjs.com/package/jAlert

**Comment by VersatilityWerks** [comment]
I take that back. Mine is out of date too. WTF. How do you update NPM?

**Comment by VersatilityWerks** [comment]
Ah found it. https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by chekovsky** [comment]
I think you have to increase the package version in your package.json file, and the run the npm publish command.

**Comment by VersatilityWerks** [comment]
Yup, seems that's the trick. I had already updated my package.json but didn't do npm publish.

**Comment by dolce** [comment]
I still had not published because I was doing some corrections and improving the plugin.
**Anyway, you can already check the version *1.1.4***
