### ISSUE TITLE
Remove console.log()

### ISSUE THREAD

**Issue by khaivngo** [dolce/iziToast#5]
Love the plugin but is there any reason for console.log('closed1'); and console.log('closed2'); being still in the code?

**Comment by lyquocnam** [comment]
+1

**Comment by dolce** [comment]
Sorry, I let it pass. I will upload the next release with this and a few more fixes, thanks! 👊

**Comment by dolce** [comment]
@kasiriveni .Fixed and released version v1.0.2! thx

**Comment by khaivngo** [comment]
Does the v1.0.2 release include the z-index fix?

**Comment by dolce** [comment]
What's the problem, @khaivngo ?
Would you like to set zIndex as an option?

**Comment by khaivngo** [comment]
Either option or increase it, reference this issue #4

**Comment by dolce** [comment]
How they closed the issue, I did not even remember.
I saw it here and the bootstrap uses "zindex: 1000;"
I'll set a larger value and the option to specify a value. ty

**Comment by khaivngo** [comment]
Glad to help!

**Comment by dolce** [comment]
Updated, check it out!
