### ISSUE TITLE
Problem with tracking.js library

### ISSUE THREAD

**Issue by stephenjason89** [dolce/iziToast#52]
when i run the script together with the library,
the timeout of the alerts prolongs almost x4

so timeout: 1000 will result to almost 4seconds

if i use 250 to create a 4 second timeout, the animation on the loading bar doesn't look as fluid as before.

**Comment by stephenjason89** [comment]
I think it's because javascript is heavily utilized with that library and setinterval does not fire up every 10ms.
It's a bit delayed so i suggest using CSS3 transitions to overcome this issue

**Comment by dolce** [comment]
Hello @stephenjason89. Try to use this version and tell me if it worked.
[iziToast v1.1.6.zip](https://github.com/dolce/iziToast/files/1229776/iziToast.v1.1.6.zip)

**Comment by stephenjason89** [comment]
[izi.zip](https://github.com/dolce/iziToast/files/1231847/izi.zip)
Hi dolce!
Thank you for the reply.
I actually just went ahead and fixed it on mine using CSS3 transitions
You can see the changes on line 307 onwards

I tried the file you sent me though. It worked too but there are some transition problems while using it with iziModal. I also have some issue with iziModal with vueJS but i'll open it on izimodal issues.

I really like your work dolce! 

Thank you for the reply.

**Comment by dolce** [comment]
Hello again.
It should work, I did not have any problems here.
And I also made improvements to the transitions and in the js.
See if unminified files work, it follows:

[iziToast v1.1.6 unminified.zip](https://github.com/dolce/iziToast/files/1232152/iziToast.v1.1.6.unminified.zip)

**Comment by stephenjason89** [comment]
Works flawless man. 
I'll use this 1.1.6 version since there are some bug fixes as well. 
I'll retire the code that i was using before the fix :)
I was using it with an ease in ease out transition instead of linear though. 

Anyway. Great job on this. 

By the way, if you have time, kindly check my issue on iziModal as well.
https://github.com/dolce/iziModal/issues/115

**Comment by dolce** [comment]
Thanks, I'll update the repository soon.
About the issue of IZIMODAL, for now I expect comments from someone who understands more about Vue.
