### ISSUE TITLE
Toast get's full height after second in IE11

### ISSUE THREAD

**Issue by simonb1978** [dolce/iziToast#53]
Hi, Great tool!

One problem, in IE11 (Chrome works fine) the toast starts small (good) but after a second it takes on the whole height of the screen. I'm using the newest version: 1.1.2
After I click on the button the notification starts on the right bottom like it should.
But than, after a second, it expands over the whole height to the top. (Untill time's up and it dissapeares.)
Anything wrong with the following: 

<script src="iziToast.js" type="text/javascript"></script>
<head><link rel="stylesheet" href="iziToast.css">
</head>
<button onclick="not();">Test</button><br><script Language="Javascript">
function not() {
iziToast.show({
title: 'Hey',
message: 'What would you like to add?'
});
};
</script>

Best regards,
Simon

**Comment by dolce** [comment]
Hello, try using version **v1.1.4**. thank you.
