### ISSUE TITLE
Toast height changed after second in chorme

### ISSUE THREAD

**Issue by bhaumik1992** [dolce/iziToast#54]
whenever i am using toast with this 
iziToast.show({    title: 'Hey',    message: 'What would you like to add?'});
 
when toast open little large height 
after second toast height normal as per showing website 

please help  
please below attachment screenshot 

First toast open with little bit large size 
![1](https://user-images.githubusercontent.com/5494833/27970750-e2ec7a56-631d-11e7-8cf1-c77a8090fb9a.png)

after second toast goes normal size 
![2](https://user-images.githubusercontent.com/5494833/27970751-e2ed7f46-631d-11e7-9d62-704b9959994f.png)

**Comment by dolce** [comment]
Which browser, version, etc.
Have you tried the version of iziToast v1.1.3?

**Comment by bhaumik1992** [comment]
I tried ver 1.1.3  . still issue as it is 
please help

**Comment by bhaumik1992** [comment]
Also tries ver 1.1.4 . still issue same

**Comment by dolce** [comment]
I need to know which version, which browser, etc ...
Because here it is normal and nobody complained about this problem.

**Comment by dolce** [comment]
I need to know which version, which browser, etc.
Because here it is normal and nobody reported this problem.

**Comment by bhaumik1992** [comment]
i did this after that it works well 
.iziToast-capsule{
height:auto !important;
}
