### ISSUE TITLE
Dark theme not working.

### ISSUE THREAD

**Issue by CubE135** [dolce/iziToast#56]
We downloaded the current js and css files and tried using the dark theme.
This is the output:
![](https://puu.sh/wKaZF/b1b4851b27.png)

Doesnt look dark to me :P

**Comment by dolce** [comment]
v1.1.4+
```
iziToast.show({
    theme: 'dark',
    message: 'Hello!',
});
```

**Comment by CubE135** [comment]
Yeah if i do that, this is the output:

![](https://puu.sh/wMQbn/72d23842c1.png)

**Comment by dolce** [comment]
version 1.1.4?

**Comment by CubE135** [comment]
Yes

**Comment by CubE135** [comment]
Ok i fixed it, Cloudflare fckd it up :D

**Comment by dolce** [comment]
-.- what was?

**Comment by CubE135** [comment]
Cloudflare kept the old version of the css file in Cache

**Comment by dolce** [comment]
I imagined.

**Comment by CubE135** [comment]
Thanks for your help tho :P
