### ISSUE TITLE
FadeOut quando Toast é aberto

### ISSUE THREAD

**Issue by projohnz** [dolce/iziToast#58]
Olá, quando chamo um toast, e ele é iniciado, os textos desaparecem.
Se eu removo a classe .slideIn dos textos e deixo a opacidade 1, eles retornam. O CSS do slidein está causando este problema.

> `.iziToast.slideIn, .iziToast .slideIn { animation: b 1s cubic-bezier(.16,.81,.32,1) both }`

**Comment by dolce** [comment]
@projohnz, Poderia criar um [jsfiddle ](https://jsfiddle.net/)com todas suas configurações?
