### ISSUE TITLE
IziToast message not getting displayed.

### ISSUE THREAD

**Issue by CubE135** [dolce/iziToast#59]
When trying to do, for examle:
`iziToast.info({
    title: 'Hello',
    message: 'Welcome!',
});`
The message is not displayed:

![](https://puu.sh/wQjOP/8b20e14a4e.png)

We use the latest Version of iziToast which is 1.1.4.
(This is happening to all toasts)
Even here: [http://izitoast.marcelodolce.com/](http://izitoast.marcelodolce.com/), the Example Info Toast does not display the message.

**Comment by dolce** [comment]
@CubE135. I tested it here on all versions and it is normal.
Try upgrading yours to v1.1.5

**Comment by vv7v7** [comment]
Firslty, make sure that you've included script. Secondly, check for unwanted comma in settings array. Then look into console's log. Hope it'll help.
