### ISSUE TITLE
Misalignment when not using any buttons

### ISSUE THREAD

**Issue by lcsphantom** [dolce/iziToast#6]
**Situation:**
When you show a toast with/without the close (x) button and without any other button or message, the title and icon of the toast are misaligned. 

**Samples:**

      iziToast.warning({
        timeout: 5000,
        title: 'Some message here.',
        position: 'centerTop',
        close: false
      });

      iziToast.success({
        timeout: 5000,
        title: 'Some message here.',
        position: 'centerTop',
        close: true
      });

Using the iziToast.settings default this seems to happen to any kind of toast.

edit: I just noticed, if I include a message in the toast, the misalignment doesn't happen.

**Comment by dolce** [comment]
I'll analyze, thank you!

**Comment by dolce** [comment]
I'll check, thank you!

**Comment by dolce** [comment]
@lcsphantom . Fixed and released version v1.0.2.
