### ISSUE TITLE
Incorrect Toast Height

### ISSUE THREAD

**Issue by rfrowe** [dolce/iziToast#60]
In Chrome 59 on macOS 10.12.5, iziToast 1.1.4 displays toasts incorrectly
![screen shot 2017-07-24 at 12 14 07 pm](https://user-images.githubusercontent.com/14118605/28540333-db9b4f94-7069-11e7-8f28-352d00e7e03d.png)
Despite the CSS rule on `.iziToast`: `max-height: 54px`, the height of the element is 71px.

This is because the default `box-sizing` value is `content-box`, so the height of the content is being set to 54px regardless of borders and margins which may add height. The most appropriate solution is to set the `box-sizing` property of `.iziToast` to `border-box`.

Result after implementing this change:
![screen shot 2017-07-24 at 12 14 15 pm](https://user-images.githubusercontent.com/14118605/28540461-5875ce54-706a-11e7-9fe2-65975abe3df1.png)

**Comment by dolce** [comment]
Yes, @rfrowe .
The error has already been fixed and will be updated soon, thanks.
