### ISSUE TITLE
izitoast hidden

### ISSUE THREAD

**Issue by nacimgoura** [dolce/iziToast#61]
Hello,
The notification is always hidden behind the elements.
![screenshot from 2017-07-27 17-28-06](https://user-images.githubusercontent.com/9990521/28681371-9447d436-72f9-11e7-97b2-e858c8b0c6cf.png)
I wish she was always ahead. Is it possible ?

Thank you!

**Comment by dolce** [comment]
Have you used the **'zindex'** option?
ex: `zindex: 999`

**Comment by nacimgoura** [comment]
I update my version and solve this issue.
Thank for your help!
