### ISSUE TITLE
Wrong timeout

### ISSUE THREAD

**Issue by vv7v7** [dolce/iziToast#63]
Dear **iziToast** devs,

Firstly, Thank you very much for this awesomeness !

( v1.1.5 )
After some time I've noticed that this awesome plugin doesn't show a notification as long as needed. As example after execution of code below it will be shown about 53 seconds, not 60. Is it ok ?

```
var value = 60;
iziToast.error( {
       id: 'type' + type,
       title: 'Error',
       message: 'Wait '+value+' seconds',
       timeout: ( value * 1000 ),
       toastOnce: true
     } );
```

Best regards,
V7

**Comment by vv7v7** [comment]
#64

**Comment by dolce** [comment]
Hello @vv7v7.
I was working on this new version, I made some improvements so I do not use any more setInterval.
Try to use this version and tell me if it worked.
[iziToast v1.1.6.zip](https://github.com/dolce/iziToast/files/1229781/iziToast.v1.1.6.zip)

**Comment by doomdrake** [comment]
Hello @dolce ,

There is a bug in v1.1.6 that you provided: hideToast crashes if you don't have a timeout attached to the toaster ( TIMER does not exist ).

All the best and thanks for making this library :+1:

**Comment by dolce** [comment]
Yes @doomdrake .
It's already fixed, try this version and tell me.
[iziToast_v1.2.0.zip](https://github.com/dolce/iziToast/files/1275248/iziToast_v1.2.0.zip)

**Comment by doomdrake** [comment]
Thanks man, it works :)

Any idea when the next official npm build will be released ?

**Comment by dolce** [comment]
This week

**Comment by doomdrake** [comment]
Hi @dolce, any news on that release ?

Sorry to pester you with this, but I'd really like to use the library through npm.

**Comment by dolce** [comment]
Update @vv7v7. Check out the **v1.2.0**
