### ISSUE TITLE
1.1.6 Error hiding instance

### ISSUE THREAD

**Issue by stephenjason89** [dolce/iziToast#66]
iziToast.show({
                        theme: 'dark',
                        icon: 'icon-person',
                        title: 'title',
                        message:'TEST',
                        position: 'center', // bottomRight, bottomLeft, topRight, topLeft, topCenter, bottomCenter
                        progressBarColor: 'rgb(0, 255, 184)',
                        timeout: 15000,
                        buttons: [
                            ['<button>Yes</button>', function (instance, toast) {
                                instance.hide({
                                    transitionOut: 'fadeOutUp'
                                }, toast, 'ok');
                                iziToast.error({
                                    title: 'Undertime',
                                    timeout: 3000,
                                    message: 'Goodbye, '
                                });

                               
                            }],
                            ['<button>No</button>', function (instance, toast) {
                                instance.hide({
                                    transitionOut: 'fadeOutUp'
                                }, toast, 'close');
                            }]
                        ],
                        onOpen: function (instance, toast) {
                            console.info('Confirm test!');
                        }
                    });

**Comment by dolce** [comment]
Fixed, thanks.
