### ISSUE TITLE
Chrome Bug

### ISSUE THREAD

**Issue by IrosTheBeggar** [dolce/iziToast#69]
There's an issues with the CSS for Chrome only that causes the height to shift.  This bug doesn't show up on Firefox at all.

I fixed it by adding this bit of CSS

```
  .iziToast{
    height: auto !important;
  }
  .iziToast-body{
    height: auto !important;
  }
```

**Comment by k-vasiliev** [comment]
Thnx for solution. I have same bug, Chrome 61, library version 1.1.5

**Comment by dolce** [comment]
Updated. Check out the **v1.2.0**.
