### ISSUE TITLE
Cores!

### ISSUE THREAD

**Issue by emtudo** [dolce/iziToast#7]
Olá Marcelo,

Novamente parabéns!

Novamente porque te dei os parabéns no facebook, e ainda relatei algumas coisas que fiz em outro plugin para adaptar as minhas necessidade. No facebook você diz que aceitaria sugestões, pois bem, vou aqui apresentar algumas que pelo menos eu estou precisando, 

1: Poder personalizar as cores do título, tanto de fundo quanto dele mesmo (sem usar class)
2: Poder personalizar as cores da mensagem, tanto do fundo quanto da mensagem (sem usar class)
3: Ter opção para não possibilitar copiar o texto (não me pergunte pq preciso disso, pq eu também não sei rsrsrs). Mas esta aqui acho que não faz muito sentido implementar não, mas talvez vc goste da ideia.

**Comment by emtudo** [comment]
Se for o caso posso lançar PR, mas primeiro preciso saber se a ideia é aceita.

**Comment by dolce** [comment]
Olá @emtudo, estou trabalhando nessa e mais algumas novidades, fique tranquilo que disponibilizarei em breve! abçs.

**Comment by emtudo** [comment]
valeu @dolce!

Muito show!
