### ISSUE TITLE
Stop timer programmatically

### ISSUE THREAD

**Issue by pbaldovi** [dolce/iziToast#71]
Hi.
Thanks for the excellent work.

A question. How can I interact with the instance? I need to stop the timer from another element. Is there any method?

**Comment by dolce** [comment]
Hi @pbaldovi, thank you!
Could you test the new version?
I made several implementations and improvements, including this one.

[iziToast v1.2.0.zip](https://github.com/dolce/iziToast/files/1308006/iziToast.v1.2.0.zip)

```
var toast = document.querySelector('.iziToast'); // Your toast selector

iziToast.progress(toast).reset();  // Reset
iziToast.progress(toast).pause();  // Pause 
iziToast.progress(toast).resume();  // Resume 
iziToast.progress(toast).start();  // Pause 
```
```
// All parameters
iziToast.progress(toast, options, callback).start();
```
```
// Example usage
iziToast.progress(toast, {}, function(){
	iziToast.progress(toast, {timeout: 20000, transitionOut: 'flipOutX'}).start();
}).reset();
```

**Comment by pbaldovi** [comment]
Hi, maybe I'm doing something wrong (1.2version)

<img width="1065" alt="captura de pantalla 2017-09-17 a la s 09 17 28" src="https://user-images.githubusercontent.com/5672385/30520686-6b9f5e42-9b89-11e7-81be-d1e0dbd06091.png">

**Comment by dolce** [comment]
Put your example online so I can see.

**Comment by pbaldovi** [comment]
I can make it work.
iziToast.progress (toast) .pause () returns undefined but pauses the timer. The problem is:

I am pausing the timer from a button that is inside the iziToast, and if I remove the mouse from the iziToast (mouseout) the timer starts to run again.
Porbé disable the property "pauseonHover: false" but the behavior is the same.

Thanks for the help

**Comment by dolce** [comment]
In this case, you should even use the **pauseOnHover: false** property.
Here it worked, see:

     iziToast.question({
        timeout: 10000,
        close: false,
        overlay: true,
        toastOnce: true,
        pauseOnHover: false,
        id: 'question',
        message: 'Working with time',
        position: 'center',
        buttons: [
            ['<button><b>RESUME</b></button>', function (instance, toast) {

                instance.progress(toast).resume();

            }, true],
            ['<button>PAUSE</button>', function (instance, toast) {

                instance.progress(toast).pause();

            }]
        ]
    });

**Comment by pbaldovi** [comment]
What's the diference betwen instance and toast vars? 
im not using "buttons:". Please see this video. 

https://share.viewedit.com/N7GjFSpJJjQnHTxL4FFdPD

**Comment by dolce** [comment]
**instance** brings all the methods of the plugin and **toast** is the DOM structure.

Thanks for the video, I understood what happens.

**Comment by dolce** [comment]
@pbaldovi. Could you see if it's all right now?
[iziToast1.2.0.zip](https://github.com/dolce/iziToast/files/1319906/iziToast1.2.0.zip)

**Comment by pbaldovi** [comment]
Work using pauseOnHover: false. With pauseOnHover: true, if i pause the timer inside the toast and leave it (mouseOut) the progress bar resume again. 

I really apreciate your help. I can use anyway with pauseOnHover: false

**Comment by dolce** [comment]
Hello @pbaldovi . I'm back.
Could you try this version again?
[iziToast v1.2.0.zip](https://github.com/dolce/iziToast/files/1348297/iziToast.v1.2.0.zip)

**Comment by dolce** [comment]
Hello @pbaldovi . I'm back.
Could you try this version again?
[iziToast v1.2.0.zip](https://github.com/dolce/iziToast/files/1350235/iziToast.v1.2.0.zip)

**Comment by codespacing** [comment]
Hi,

I use the same code but still have issues with version 1.2 & 1.3. 

Error:

> Uncaught TypeError: Cannot read property 'querySelector' of undefined 
> at Object.$iziToast.progress (iziToast.js:394)
> at HTMLButtonElement.<anonymous> (iziToast.js:917)

The code:

```
iziToast.question({
    timeout: 10000,
    close: false,
    overlay: true,
    toastOnce: true,
    pauseOnHover: false,
    id: 'question',
    message: 'Working with time',
    position: 'center',
    buttons: [
        ['<button><b>RESUME</b></button>', function (instance, toast) {
           
            instance.progress(toast).resume();

        }, true],
        ['<button>PAUSE</button>', function (instance, toast) {

            instance.progress(toast).pause();

        }]
    ]
});
```

Can you please help with this?
