### ISSUE TITLE
how to use this in a react project?

### ISSUE THREAD

**Issue by JHanLu** [dolce/iziToast#76]
After npm install, how to import this into my JS files( using es6 )? According to your instruction, you need to include the CSS and JS files from the dist folder which is in the node_moudules folder, so when i run _npm run build_, will it works?

**Comment by JHanLu** [comment]
você não pode falar inglês?

**Comment by CeoFred** [comment]
Well,only the js file is imported when you require izitoast, the CSS isn't loaded.. To do this, simply copy the minified CSS(recommended) from node_modules to a folder or choice inside your SRC folder and import this CSS file in your app.js or index.js in your root directory in SRC folder,enjoy!
