### ISSUE TITLE
How to create a custom closing button

### ISSUE THREAD

**Issue by stefanreimert** [dolce/iziToast#77]
I want to create a custom closing button.
The code is below and i hope someone can help me with this.
The button in the buttons property needs to replace the button with the clse-btn class.

`
iziToast.show({

    timeout: 1000000,

    resetOnHover: true,
    transitionIn: 'fadeIn',
    transitionOut: 'fadeOut',
    message: '<div class="notification-edit"><div `class="grid-x"><div` class="cell auto"><div class="notification-edit__content"><p><strong class="primary">Let op!</strong> Je hebt dit onderdeel nog niet ingevuld.</p></div></div><div class="cell shrink"><button class="close-btn">Custom closing button</button></div></div></div>',
    close:'false',
    buttons: [
        ['<button class="button white-button"">Sluit notificatie <span aria-hidden="true">&times;</span></button>', function (instance, toast) {
            instance.hide({
                transitionOut: 'fadeOutUp',
            }, toast, 'close', 'white-button');
        }]
    ],
});
`

**Comment by dolce** [comment]
You can customize buttons using CSS.
But you should always use the 'buttons' option.
Thank you.
