### ISSUE TITLE
Incompatibilidade ao usar iziToast com Izimodal

### ISSUE THREAD

**Issue by leozoccoli** [dolce/iziToast#79]
Boa tarde, tudo bem? 

Parabéns pelos trabalhos realizados, são fantásticos.
Quando tento usar os dois módulos criados por você, estes dão incompatibilidade no css, deixando as janelas do izimodal meio malucas ao abrir.

**Comment by dolce** [comment]
Obrigado @leozoccoli !
Tente usar a versão **1.2.0** e me diga se resolve:
https://github.com/dolce/iziToast/releases/tag/v1.2.0

**Comment by leozoccoli** [comment]
[exemplo.zip](https://github.com/dolce/iziToast/files/1368665/exemplo.zip)
Bom dia.
Acabei de fazer os testes e ainda dá conflito nas animações do izimodal com izitoast
Ao abrir e fechar a janela do izimodal ela pega uma animação errada e confusa. Fica como se ficasse balançando de um lado para o outro e na hora de fechar faz a animação também e demora a fechar a janela. 
Sem o css do toast o izimodal fu

nciona perfeitamente.
O teste que estou fazendo é bem simples só com os parâmetros default dos dois módulos. 
Coloquei um video no zip se quiser verificar o efeito.

**Comment by leozoccoli** [comment]
@dolce usando o .min.js e .min.css o erro ocorre, agora quando uso somente o .js e .css não ocorre o problema. 
Vi que dentro do .min está com código html, é assim mesmo?

**Comment by dolce** [comment]
Olá @leozoccoli .
Não, em qual arquivo tem html no css minificado?

**Comment by leozoccoli** [comment]
[arquivos.zip](https://github.com/dolce/iziToast/files/1369974/arquivos.zip)
@dolce tem html no css minificado e também no js minificado. 
em anexo os dois arquivos com html.

**Comment by dolce** [comment]
Negativo @leozoccoli. Onde baixou esses arquivos?
Segue a release correta. Veja se com estes arquivos ainda está corrompendo as animações:
https://github.com/dolce/iziToast/releases/tag/v1.2.0
