### ISSUE TITLE
Question method is undefined 

### ISSUE THREAD

**Issue by Ridermansb** [dolce/iziToast#80]
I'm trying to use with React

`import iziToast from 'izitoast';`

![screen shot 2017-10-06 at 09 33 08](https://user-images.githubusercontent.com/725337/31277909-7f225560-aa79-11e7-88a6-081b6d3c3ff0.png)

> "izitoast": "1.1.5",

**Comment by dolce** [comment]
@Ridermansb, o toast do tipo **Question** só está disponível na versão **1.2.0**.
Faça o teste me diga se está funcionando:
https://github.com/dolce/iziToast/releases/tag/v1.2.0
Obrigado.

**Comment by Ridermansb** [comment]
Vou tentar.

PS: A versão publicada no npm é a 1.1.5.

**Comment by Ridermansb** [comment]
Mesmo erro.

question não está definido em https://github.com/dolce/iziToast/blob/master/dist/js/iziToast.js

**Comment by dolce** [comment]
Funcionando aqui.
O único método existente é o .**show**, os métodos `info`, `success`, `warning`, `error `e `question`. são apenas aliases.
