### ISSUE TITLE
Settings are ignored.

### ISSUE THREAD

**Issue by chrismartinez99** [dolce/iziToast#81]
This could be a documentation issue, but "Settings is used to set default values" implies that settings would be used globally. However, this does not seem to be the case.

Here are the issues with the code from below:
- Overlay missing - are the settings ignored? I've tried setting the overlay on the specific instance and have not seen the overlay working. 
- Close On Escape does not function
- When using iziToast.question, I receive "Uncaught TypeError: iziToast.question is not a function"  error in console.

```
iziToast.settings({
    timeout      : 5000,
    resetOnHover : true,
    closeOnEscape: true,
    transitionIn : 'fadeIn',
    transitionOut: 'fadeOut',
    position     : 'center',
    overlay      : true,
    overlayClose : true,
    overlayColor: 'rgba(0,0,0,.8)'
});

$('body').on('click',function(e){
    iziToast.show({
        close: true,
        toastOnce: true,
        zindex: 999,
        title: 'Hey',
        message: 'Are you sure about that?',
    });
});
```

I am using NPM install version 1.1.5.

**Comment by dolce** [comment]
Exactly @chrismartinez99 , all these features are only supported in version 1.2.0,
thank you.

**Comment by chrismartinez99** [comment]
Aah! Ok, I'll give that a shot. 
The default NPM install is 1.1.5 so I don't know if that is something that you need to change.

Thanks!
