### ISSUE TITLE
Toast not disappearing after delay elapsed

### ISSUE THREAD

**Issue by willfergus-boston** [dolce/iziToast#82]
Toast messages with a settings, timeout value of < 1000 do not disappear automatically.
Mousing over the toast will cause it to disappear.

This occurs with version 1.2.0, not 1.1.5.
Have tested in multiple environments.

Settings example:

```javascript

var settings: IziToastSettings = {
            timeout: 500,
            title: "test",
            message: "test",
            layout: 2,
            maxWidth: 500
        };

iziToast.success(settings);

```

**Comment by dolce** [comment]
I'll check, thanks

**Comment by dolce** [comment]
@willfergus-boston. Package updated. Can you see if it's okay now?
https://github.com/dolce/iziToast/releases/tag/v1.2.0

**Comment by willfergus-boston** [comment]
@dolce Can confirm this is fixed in the latest version. Thanks. Closing the issue.
