### ISSUE TITLE
Two prompt boxes will pop up, and one will not disappear

### ISSUE THREAD

**Issue by lxt410725** [dolce/iziToast#84]
I'm a message trigger, two messages are coming at the same time, and two prompts pop up at the same time, but after a certain amount of time, there's another one that won't automatically close

**Comment by kaddy645** [comment]
Facing the same issue..did you get any alternative solution @lxt410725

**Comment by dolce** [comment]
I did not understand.
Send the snippet of code that you are using.

**Comment by kaddy645** [comment]
izitoast.show({
      class:'Note',
      title: 'Note',
      titleColor: 'white',
      message: "hello",
      position: 'center',
      backgroundColor: '#925619',
      close:true,
      progressBarColor: 'white',
      messageSize: '15px',
      messageColor: 'white',
      timeout: 2000,
      transitionIn: 'fadeInRight',
      layout: 2,
      maxWidth: '500px',
      toastOnce:false,
      pauseOnHover: false,
      id: 'toastOne',
      balloon: true,
   
    });

 if there two different (i am using angular here) components and if in each of them i am using izitoast 
 show..both of them have different id's (toastOne and toastTwo respectively) if the Timeout is same 
 lets say 2000ms , it will  prompts two pop up at the same time, but after a  delay is over , it will 
 close one of them it will still show one of them
 for both of them i am using izitoast.hide(toastOne) And izitoast.hide(toastTwo).

**Comment by Nnayl** [comment]
Hi,

Have same trouble with izitoast.show() on a javascript loop.

`for (var i = 0; i < 4; i++) {
              iziToast.show({
                  id: null,
                  class: '',
                  title: 'Hey',
                  titleColor: 'red',
                  titleSize: '',
                  titleLineHeight: '',
                  message: 'my first izitoast notification',
                  messageColor: '',
                  messageSize: '',
                  messageLineHeight: '',
                  backgroundColor: '',
                  theme: 'light', // dark
                  color: 'red', // blue, red, green, yellow
                  icon: 'material-icons',
                  iconText: 'done',
                  iconColor: 'red'
              });
          }`

**Comment by Nnayl** [comment]
Actually my alternative solution is to use SetInterval() instead a consensual loop.

`var alert = [
              { title: 'titre 1', message: 'message 1' },
              { title: 'titre 2', message: 'message 2' },
              { title: 'titre 3', message: 'message 3' }
          ]

          var i = 0;
          var interval = setInterval(function () {

              if (i >= alert.length) {
                  clearInterval(interval);
              } else {
                  iziToast.show({
                      id: i,
                      class: '',
                      title: alert[i].title,
                      titleColor: 'red',
                      titleSize: '',
                      titleLineHeight: '',
                      message: alert[i].message,
                      messageColor: '',
                      messageSize: '',
                      messageLineHeight: '',
                      backgroundColor: '',
                      theme: 'light', // dark
                      color: 'red', // blue, red, green, yellow
                      icon: 'material-icons',
                      iconText: 'done',
                      iconColor: 'red'
                  });
                  i++;
              }
          }, 200);`

**Comment by ShawnMcGrory** [comment]
Same issue here. If two different iziToast alerts are shown at the same time, only one will disappear, the other will become stuck. Additionally, the one that stays cannot be closed using the close button.

**Comment by dolce** [comment]
Thanks for reporting, I've already identified the problem, I'll fix it.

**Comment by dolce** [comment]
Could you test this version?
https://github.com/dolce/iziToast/releases/tag/v1.2.0

**Comment by dolce** [comment]
@ShawnMcGrory @Nnayl @kaddy645 @lxt410725

**Comment by ShawnMcGrory** [comment]
@dolce The issue seems to be resolved with the update. Thank you!

**Comment by Nnayl** [comment]
Hi,

this problem come back with the 1.3 version :(
My fix with interval statement not work too

**Comment by dolce** [comment]
@Nnayl,
Can you upgrade your package and test again?
https://github.com/dolce/iziToast/releases/tag/v1.3.0
Thanks.

**Comment by Nnayl** [comment]
Hi,

Work fine.
My bad, whit 1.3 it was broken only on chrome and the origin of problem was a conflict with a chrome extansion (AD block)

Thanks you :)
