### ISSUE TITLE
Buttons API expects a Class to be provided as second param

### ISSUE THREAD

**Issue by purtuga** [dolce/iziToast#89]
Looks like the function provided to each defined button MUST be a `class` - is that the expected behavior?

The following causes an exception because arrow functions are not allowed to be constructors:

```javascript
iziToast.show({
    title: 'Hey',
    message: 'Welcome!',
    buttons: [
        ['<button>Ok</button>', (instance, toast) => {
            alert("Hello world!");
        }]
    ]
});
```

A similar example with non-es6 code would be:

```javascript
var myObj = {
    go: function() { alert("go called"); },
    callGo: function(){ this.go(); }
}

iziToast.show({
    title: 'Hey',
    message: 'Welcome!',
    buttons: [
        [ '<button>Ok</button>', myObj.callGo.bind(myObj) ]
    ]
});
```
The issue is at [line 899](https://github.com/dolce/iziToast/blob/master/src/js/iziToast.js#L889), where you are calling the button's callback function as a cunstructor: 

```javascript
    new ts(that, $DOM.toast);
```

Is this a bug?
I can contribute the fix if you like.

**Comment by dolce** [comment]
Hello @purtuga.
Yes, thank you for notifying me, I made the correction and will be updated already in this version v1.2.0.

**Comment by dolce** [comment]
Could you test and tell me if it's okay?
https://github.com/dolce/iziToast/releases/tag/v1.2.0

**Comment by purtuga** [comment]
Oi Marcelo.
Thank you for the quick response. Yes, that fixes the issue.
Thanks again for help in this and for sharing such a great library.

Paul

-- sent from mobile
