### ISSUE TITLE
zindex in 1.2.0

### ISSUE THREAD

**Issue by Lunatig** [dolce/iziToast#92]
in version 1.1.5 all toast were in front of all elements.
but in 1.2.0 some elements in front of toast and i need to set zindex manually. that's a pity

**Comment by dolce** [comment]
@Lunatig. This happens because you must have many elements with z-index above 999. And this is bad practice. Review your code.
You can also configure your iziToast globally.
```
iziToast.settings({
    zindex: 99999
});
```
Anyway, I will also increase the number in the plugin.
