### ISSUE TITLE
base64 image string

### ISSUE THREAD

**Issue by dougroutledge** [dolce/iziToast#93]
Unlike a normal html img tag, the image doesn't seem to display a base64 image string.

**Comment by dolce** [comment]
Fixed @dougroutledge . Could you test?
https://github.com/dolce/iziToast/releases/tag/v1.2.0

**Comment by dolce** [comment]
Fixed @dougroutledge . Could you test?
https://github.com/dolce/iziToast/releases/tag/v1.2.0

**Comment by dougroutledge** [comment]
Still having the issue.  No image displayed only the background.

**Comment by dolce** [comment]
Send me your config so I can test it.

**Comment by dougroutledge** [comment]
var img = "data:image/png;base64, /9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCABgAGADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD2g9unT0pPy/KnHr+FGKYDcn2/Klyfb8qXFY/ifVBo/h+6uQ2JipSIDqWP+c0m7IaV3YdqfiXR9IgaW7v4BtbbsjId8+m0c1i3HxK8PwH5GuJuAfkiwP1xXmMEMTWonkiQTOMlwPvCsbUZgPlzj05rL2l9jb2SS1PcNL8f+H9TlWIXf2eRjgLcLsBPpnpXUA/T8q+TxdPG/wB7jvXqnw88ePE8ek6lLm3YhIZGP+rPYE/3T+lWpdyJQ7Hrufp+VH5flSilqzMOfQflT0PPb8qZT160ARHr+FLikPX8KcKQxuK8+8cXS3dxLblh5Vsm3r1duT+mK7+aRYYXkb7qgk141f3Lanq9hCSf9NundvcDpWNeVom+HhzSuXdB8O3R0xjJkRu2U9hWJrfg6VizIwz27V6+bZbWwEajAVcAVzOoYZWLYGK4+eSdztSi9DwLUbG40+fY4PGRn1qfTpmyuOq4PTtn+hrrPEWmwziQ+am9uVXPJNcvpds4uEYjhH2v9Dwf6flXVCfNHU5pw5ZaH0X4G1htX8OxGVsz2/7qTPU46H8v5V0nevK/h9eHT9aSzZvkuYyv/AlP/wBavVa2g7o5qitIUdakTrUajmpkFWQQEc/hRSnr+FJikMxPFdw0Hh28KHDGMrn615NpEh/4STQZCrMI0lcgdTxXrXieAz6HcL7V5ZpZjtPHXh+N2wJDNGM+pXgfpXJiL3OzDWsO1rxVr76iEtrTUIrdnIAkcA8d9pFbuuQXH9g213K7KZF+dR16V0etzWkGGl2kEjg85ql4juLea0t7dJE8wYJjB+7x39KwvdpHSk0jx3+ztWumWe3ZgrOSVU547ZJFacejzWy3FyybgV3OAMduTWyLk6bO0BA8ojcrJyBntWpAon0q7LOpV4n/AAG01spSvZmcoK1zOtnaGW2v4iA0dyrZ7fMA3+Ne1RP5sSOB95Qa8Z8OQm+8KzM3LCGFxn1xxXsdgpFjAD1CDP5VvTerOOrsiyoqRRz+FNFPXrWxiVu/4UtJ/hS96QyC5iEtvJGwyrKQRXgnjgT6Prmn3kQJkspw6gd9pBx+IyK+gXHy15T8QLBLt3niwWVsZ9xXPiGlZnRh7u6I9TS41S907U7LF5ZzDdHC0mwbuoyf88itDVLae902K5ltrKxuAuZFaQhkPQ5I+9iuS8N6+LGNI5QTbmULIijBRuzAfzH413er6dbatbCRJyFIydrYzXGtHY9FST3OGdb6dRBpc6GUvme7MO5EQdcFurGq892+g+CbiSRj9onDRxg92bI/xNbcSW2mRSiW4SK0jO6RieP/AK9cVr2or4h1nTYIgy2oYsin+7nG4j3wa6lZpHNN2bseg+FIktdCkhb+GKAH8AK9RsJlmtldfpXklpcgadeunO4L/wChcfpXb+D9WW5hEDN8zLkZ9RxVU5anPVjodctSoOfwqJamTrXScxWWJ5D8o49TVK/a6tomeJojgZ+bitkAIoA6VzGuSvKqwqSAWyffnpWNR2jc1pq8rHH634uv4UaLzSgIxkCsKDVlvBPazNncxwW9wMGptatHleSWXCpHkjPT8a5+1tikbTZbBYYJ6nOef5V5vM56tnpqMYrQrXVm0V64VSrEgHHqDXbqqvpio7fMEAJBxWXb27atGJVVfMVsMT3OTVh476yxHc20sfHVlOD+PSjVj0RwHiGKU3LIZZHRTwGbIFS6FYmYXV8f+WEQVPx4ra13T3Nt5+3l2wOOtO8MWMp0bUneNliAG0kcMc8/0rZT90zlHUtaIxli1S1/vJuT2xj/AOtTvD+qXCWazWmTc20m9VHU4+8Khtg1ubmVMqziRfzUEfyrnfDuoz2ussuWUu+4EHGCe9XF3VzKSs7H0boWsW2uabHd2zA7h86Z5Q9wa1l614voTXdpdyXtheukhY+YjdGPvXpuha//AGkvl3EXkzqOSPut9K6oTvozknTtsajXIeZEHc1mSwK1zBuHAVmP50y1lZ75Cf4jmtCSL967cfJB60pLmQL3WeceKrN/sqjHyk5YDv3xXOXy+Vc2VsgwCmXA9zj9MGux8XSm1s432F5QcRRjq7np+HeuZ+wyqwXO544kjLt3bHzGvL2bPSWqVx3h+dbQy4BbMyhR+dej6rOVi8lEBQKMD14rzrSLUm6iCksBJuJx1Nd5eElVz2UCu3DRscuId2cXPHIbgKULcnapIOK0bqUnS7nag8uCNRx3ORmrBtyzs+Mk9KdNF5FmYdud4+bFXWhaLsTTndo5O5jH9kS3QHDwmQfUcVw1mDFqSzn/AFbIpb27cfp+deh3dhPNpa6VEjGQttz6Anr+lZd14eFq3yruXgPj6YP6fqBXLCdonRKN2aHh6R/LHm8uxKsfUiu60WdLe4dGAaNjgg1wfh9WH7iUfNE/ze+On6V1Fu0kd9t6fNnmu+hrDU46ytI//9k=";

var msg = "Test Message";
var title = "Test Title";

iziToast.show({
        id: null,
        class: '',
        title: title,
        titleColor: '',
        titleSize: '15',
        titleLineHeight: '',
        message: msg,
        messageColor: '',
        messageSize: '15',
        messageLineHeight: '',
        backgroundColor: '',
        theme: 'dark', // dark
        color: '#3F6BC3', // blue, red, green, yellow
        icon: '',
        iconText: '',
        iconColor: '',
        image: img,
        imageWidth: 50,
        maxWidth: 400,
        zindex: 99999,
        layout: 2,
        balloon: true,
        close: false,
        closeOnEscape: false,
        rtl: false,
        position: 'bottomRight', // bottomRight, bottomLeft, topRight, topLeft, topCenter, bottomCenter, center
        target: '',
        targetFirst: true,
        toastOnce: false,
        timeout: 30000,
        animateInside: true,
        drag: true,
        pauseOnHover: true,
        resetOnHover: false,
        progressBar: true,
        progressBarColor: '',
        progressBarEasing: 'linear',
        overlay: false,
        overlayClose: false,
        overlayColor: 'rgba(0, 0, 0, 0.6)',
        transitionIn: 'fadeInUp',
        transitionOut: 'fadeOut',
        transitionInMobile: 'fadeInUp',
        transitionOutMobile: 'fadeOutDown',
        buttons: {},
        onOpening: function () { },
        onOpened: function () { },
        onClosing: function () { },
        onClosed: function () { }
    });

**Comment by dolce** [comment]
Remove the space after 'base64'
![image](https://user-images.githubusercontent.com/2837790/32510867-2866e500-c3d9-11e7-8d1b-b75fb8e8e80b.png)

You can also use without the beginning of the string: **_data:image/png;base64_**
![image](https://user-images.githubusercontent.com/2837790/32510954-851e8744-c3d9-11e7-99cf-b4d418145991.png)

**Comment by dougroutledge** [comment]
Thank you.

**Comment by dolce** [comment]
Was the space?

**Comment by dougroutledge** [comment]
yes I removed the space and it works.  I didn't realize that was an issue, since the HTML IMG always displays normal.

**Comment by dolce** [comment]
https://github.com/dolce/iziToast/releases/tag/v1.2.0
I made other adjustments, use this latest version.
Soon I will publish on npm.
thank you.
