### ISSUE TITLE
Import in Typescript

### ISSUE THREAD

**Issue by gama410** [dolce/iziToast#95]
Hello,

Since upgrading to 1.2, I can't find a way to properly import izitoast in a typescript file.

I would like to be able to use a simple  **import {IziToast} from 'izitoast';**

but now I get error messages either when transpiling to javascript (izitoast doesn't export IziToast) or at runtime (no method 'success' of undefined) whatever type of import I'm using:

**
import {IziToast} from 'izitoast';
import * as IziToast from 'izitoast';
import IziToast from 'izitoast';
import IziToast = require('izitoast');
**

Do you thing there is a correct way to do that that I cannot find or shall I revert back to v1.1.5?
Thanks a lot!

**Comment by dolce** [comment]
Please, use this issue #73

**Comment by HamedFathi** [comment]
@gama410 @dolce 

Hi
seems someone changed it to the new version!

now it has `export default`, 

```
declare const iziToast: IziToast;

export default iziToast;

export {
    IziToastPosition,
    IziToastTransitionIn,
    IziToastTransitionOut,
    IziToastSettings
};
```

so use it like

![2017-11-22_17-46-06](https://user-images.githubusercontent.com/8418700/33132071-beb2ebf0-cfad-11e7-89a9-59f4a3f4c7d2.png)

I think this change has troubles for those using the previous versions, but it is a very good change. Because you already have the rest of the classes as exported.

**Comment by fhurta** [comment]
There's also option to import it like this:
`import { default as iziToast, IziToastSettings } from 'izitoast';`
 and then use `iziToast`.

I'm not Typescript guru but I would avoid default export at all and exported all types the same.

**Comment by gama410** [comment]
Thanks guys! I had already tried the first option (import * as izitoast) but, even though typescript didn't complaint, the transpiled JS failed at execution type because izitoast was undefined...

I'll have to try the second option from @fhurta and I'll come back to you when I'm done!

Thanks a lot!

**Comment by fhurta** [comment]
@gama410 you would probably need to import the library itself with `import 'izitoast';` as well. The import above only import the types so Typescript knows its signatures

**Comment by gama410** [comment]
Ok, I finally got back to this issue (sorry for the delay)!
So I tried the following options but without luck, unfortunately. I'm reverting back to 1.1.5 for the moment...
`
import {default as iziToast} from 'izitoast';`
TS doesn't complain but JS fails with a "warning of undefined" when I do "iziToast.warning()"


`import * as iziToast from 'izitoast';`
TS complains that "success, info, etc" don't exist on iziToast. BUT JS works just fine...

If I leave that import but replace all calls by iziToast.default.success(), TS doesn't complain but JS fails...



@fhurta are you sure about that? As far as I know, all libraries are correctly imported. And actually, the izitoast lib is added to my bundles and sent to the client.

**Comment by fhurta** [comment]
If you comment out the imports you mentioned, is the izitoast still included in your bundle?

**Comment by mourad1081** [comment]
Hello, it works just fine for me if I do
`import 'izitoast'`

Here is how I use it somewhere in my code : 

```javascript
...
import 'izitoast'
...
export class Notification {

    constructor(title:string, message:string, type:TypeNotification) {
        let settings: IziToastSettings = {
            title: title,
            message: message,
            position: 'topRight'
        };

        switch(type) {
            case TypeNotification.Info:        iziToast.info(settings); break;
            case TypeNotification.Success:  iziToast.success(settings); break;
            case TypeNotification.Warning: iziToast.warning(settings); break;
            case TypeNotification.Error:       iziToast.error(settings); break;
        }
    }
}

```

**Comment by gama410** [comment]
Hello,

I come back with this issue. I know it's been an awfully long time but as I had found a workaround, it just remained on the side...

So I still have the problem here in v1.3.0. I dug a little deeper and got some more information :

I need to import izitoast this way : _import * as iziToast from 'izitoast';_ in order to be able to use this line of code: _iziToast.info(...)_ 
Note that I can also import the other interfaces like this: _import { IziToastSettings} from 'izitoast'_ but as they are only interfaces, they have no impact over the compiled javascript code.

Now, I use AMD to load my modules and the compiled javascript looks like this:

`
define('code/tools/toast', ["require", "exports", "izitoast"], function(require, exports, iziToast) {
    "use strict";
    Object.defineProperty(exports, "__esModule", {
        value: true
    });
    var Toast = (function() {
        function Toast() {}
        Toast.success = function(msg, title) {
            if (title === void 0) {
                title = '';
            }
            iziToast.success({...
`

whereas if I import with _import {default as iziToast} from 'izitoast'_, the generated Javascript tries to use the default export : _izitoast_1.default.success(...)_ which doesn't work as _izitoast_1_ is already the reference I need.

I'm pretty sure this is a problem coming from some inconsistency between izitoast's code for amd & the d.ts file but I don't know enough about the subject to find a fix for this...

For now, I fixed my problem by casting izitoast to any so the compiler doesn't complain... If you ever find out how to fix this problem, I would love to see the solution! 

Apart from that, izitoast is awesome : thanks for your work!

**Comment by babruix** [comment]
`import * as iziToast_default from 'izitoast';
const iziToast = iziToast_default.default;`
Then you can get intelligence in IDE:
![screen shot 2018-07-06 at 17 15 10](https://user-images.githubusercontent.com/462976/42386602-3ac377c0-8140-11e8-9b6f-51cfc438925a.png)

**Comment by babruix** [comment]
@davidsk Try this:
```
import * as iziToast_default from 'izitoast';
const iziToast = iziToast_default.default || iziToast_default;
```
