### ISSUE TITLE
Typescript typings do not match the JS interfaces

### ISSUE THREAD

**Issue by fhurta** [dolce/iziToast#96]
After upgrade to version `1.2.0.` (from `1.1.5`) I wanted to use typings.

Started with method `hide()`. While in JS it is defined as 

    $iziToast.hide = function ($toast, options, closedBy)

In typings it is as

    hide(settings: IziToastSettings, toast: HTMLDivElement, closedBy: string): void;

Note the swapped parameters.

**Comment by dolce** [comment]
Thanks, @fhurta, I'll fix it.
