### ISSUE TITLE
Uncaught TypeError: Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by joepsyko** [dolce/iziToast#97]
I upgraded from 1.1.5 to 1.2.0 and now I have the following issue.

When executing **instance.hide()**

```javascript
buttons: [
    ['<button>Dismiss</button>', (instance, toast) => {
        instance.hide({
            transitionOut: 'fadeOutUp',
            onClosing: (instance, toast, closedBy) => {
                // ...
            }
        }, toast, 'close', 'btn2');
    }, true],
],
```

I have the following error:
**Uncaught TypeError: Cannot read property 'add' of undefined**

Here is the line:
```javascript
$toast.classList.add(PLUGIN_NAME+'-closing');
```

Anyone had the same problem?

**Comment by ferdiebergado** [comment]
I also have the same problem.

**Comment by dolce** [comment]
I'll check, thank you.

**Comment by joepsyko** [comment]
It works, thank you!

**Comment by vagh** [comment]
@dolce This problem is also in current vrision on your document, Hope you can modifiy this example code.
